# declare the variables
# CC=clang++
CC = cl

# default commands
all: no121
	
# LC problem 121
no121: ../includes.h
	$(CC) no121_BestTimetoBuyandSellStock.cpp -I ../includes.h -o no121

# LC problem 198
no198: ../includes.h
	$(CC) no198_HouseRobber.cpp -I ../includes.h -o no198

# clean all the executables
clean:
	rm -rf *o no121 no198